version: '3.3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - '${PHPMYADMIN_PORT_INSTANCE}:${PHPMYADMIN_PORT_IMAGE}'
    depends_on:
      - mysql

volumes:
  mysql_data: {}
