name: CI/CD Frontend React (Guacamaya Airline)

on:
  push:
    branches: [ feature/cicd_frontend ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install

      - name: Generar build
        run: |
          npm run build


